### ISSUE TITLE
Failed build in MacBook M1

### ISSUE THREAD

**Issue by brianignacio5** [codrsquad/portable-python#1]
```
-- 2 problematic
_gdbm*.so /usr/local/opt/gdbm/lib/libgdbm.6.dylib:7.0.0
_dbm*.so /usr/local/opt/gdbm/lib/libgdbm_compat.4.dylib:5.0.0
```

System python used is Python 3.9.6.

Maybe I'm missing something in my system ?

**Comment by zsimic** [comment]
Yes, I've been trying to find a good way (without patching files..) to tell `setup.py` NOT to look at `/usr/local`, but there is no great way yet that I found.

You can include gdbm IIRC to work around this issue, ie:
```
portable-python build 3.9.6 -mxz,openssl,gdbm
```

But if you do, I think then `_dbm` will show as absent...

Still looking for a solution on this. Best would be to find an elegant way of telling the python compilation machinery NOT to look at `/usr/local`...

One way to "fool it" for now would be to do this in your `portable-python.yml` config (because of https://github.com/python/cpython/blob/main/setup.py#L82): 

```
macos:
  arm64:
    env:
      _PYTHON_HOST_PLATFORM: darwin
      MACOSX_DEPLOYMENT_TARGET: 11
```

(you'd need to repeat the MACOSX_DEPLOYMENT_TARGET var, since my config mechanism is very rudimentary currently).

I don't have my M1 handy right now to try this, but I think the `_PYTHON_HOST_PLATFORM` env var will do the trick.

Note that you don't have to use the `.yml` config, you can also do:

```
_PYTHON_HOST_PLATFORM=darwin portable-python build 3.9.6
```

**Comment by zsimic** [comment]
If I don't find anything better, I may simply set that `_PYTHON_HOST_PLATFORM` env var internally to avoid this "picking up `/usr/local` business :) ).

**Comment by zsimic** [comment]
Well, just tried and now I remember why I didn't set `_PYTHON_HOST_PLATFORM` already: if that env var is set, then *all* components must be statically compiled, and the setup then doesn't find any macos system libs...

Note that the 2 issues reported by the `inspect` you reported here are "soft" -> your compiled binary is indeed not fully portable, *but* only the seldom used `_gdbm` and `_dbm` modules won't be available at runtime... (unless one has the same brew installation as you).

So, you can ignore those probably for now (until I find a proper way to let `setup.py` know to ignore `/usr/local`).

I will try and address this in the near future

**Comment by zsimic** [comment]
Try the latest version again -> it should now compile correctly without using `/usr/local`

I'm patching out mentions of `/usr/local` now, I think it actually has to be done, otherwise picking up unexpected/dynamic stuff like that can sneak in...

**Comment by zsimic** [comment]
I've confirmed on M1: version `1.1.1` fixes this completely, please reopen if you still see an issue
