### ISSUE TITLE
Is it possible that tcl/tk will build on a mac that is configured just to build portable-python? 

### ISSUE THREAD

**Issue by paulmromer** [codrsquad/portable-python#5]
If I use a Mac that has might have nothing else installed, so nothing in /usr/local; and that might have an updated version of tcl/tk installed, that portable-python will build with support for the included tcl/tk? Re the updated version of tcl/tk, if I am building a portable version of 3.10.4, I could install the regular install of this version of Python first. 

I have a Arm iMac that I can easily reset to factory default. Would it be useful for me to try some experiments? If so, what would you suggest? Is the main issue to get the right settings on compiler flags? 

I realize that this will not solve the more general problem of having a version of pp that will run on most user machines. But for me, it would still be helpful to create a build of pp that I could sign and then move to other machines I am using.

**Comment by zsimic** [comment]
Do you mean you want to build a python binary that has references to shared libs? In your case tcl/tk?
That in theory is well supported, there is just a "default assumption" that you want a clean portable python that does NOT refer to any shared libs a user may not have.

You can configure things such as shared libs are OK, with `allowed-system-libs: .*` (it's a regex you can fine-tune).
That `allowed-system-libs` thing is just for the validation step after the build.

**Comment by zsimic** [comment]
The general philosophy is to try and use the upstream `./configure` scripts as-is, as much as possible.
For the main use-case (get a real "portable" python build), some isolation is attempted, but even that can be fine-tuned/configured further, to allow also for "yup, I'm OK with it not being 'purely portable'". That part may need a bit of work, but I think it's very doable :)

I did try to account for that case, where it is OK to have it refer to some shared libs.

The `inspect` command tries to make evident those shared libs, and a "validate" step checks against the config what is OK and what is not (so that you don't get a build out that uses some shared libs that you didn't want)

**Comment by zsimic** [comment]
Yes, `portable-python` is intended to work that way: build on one machine, then install that on N machines (and when the produced tarball is truly portable, then the installation can be as simple as "unpack in some folder - any folder, and it'll just work from there). That's how I use it :)

One could also I guess "build on-the-fly" on each machine, but then if one does so then the "portability" is moot... since it was built on the target machine where it'll run, the fact that it is "portable" is over-kill in a way... (ie: you don't really need `portable-python` then one could argue...)

So yes, `portable-python` is intended to work like that (build once, install many times).

**Comment by zsimic** [comment]
Regarding tcl/tk, I did try originally to allow for it to be included just like all the other components are: `openssl` etc.
However, it turned out that tcl/tk is hard to build, especially on linux :( 
So I moved the tcl/tk code to here: https://github.com/codrsquad/portable-python/tree/main/retired

Awaiting to get some time again to try and get to the bottom of it (how to make it build properly, by delving into it doc).

We can try and make a branch where we try to resurrect it.

**Comment by zsimic** [comment]
I'll try and resurrect the tcl/tk code, it should be OK to include it, provided it doesn't get "auto-selected" (and requires explicit opt-in basically, via config or command line args).
Once I do that, you can play with it and try to make the C compilation work :) (just gave it a quick try, and it fails miserably even on mac now)

**Comment by zsimic** [comment]
I've re-activated tcl/tk: https://github.com/codrsquad/portable-python/commit/c1e223417159e764313dc3b853fd3d7c968ec116

I've also released portable-python 1.4.3, you can now try for example: `portable-python build 3.10.5 -mtkinter`, and then look at `build/cpython-3.10.5/logs/` to see why it didn't pick it up :)

You'll see that apparently even with the documented `--with-tcltk-includes=` etc passed to cpython's `./configure`, it still seems to ignore that, and eventually ends up using `/Library/.../MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Headers` etc

**Comment by zsimic** [comment]
I tried with 8.6.12, but that fails to C-compile (C compilation errors).
8.6.10 C-compiles at least, but ends up being ignore anyway.

**Comment by zsimic** [comment]
I've added this file in case it helps, on how to run `portable-python` in the debugger, the tests etc: https://github.com/codrsquad/portable-python/blob/main/DEVELOP.md
